"""Knowledge graph: concepts as nodes, prerequisites as edges.

This is what separates Sensei from a chatbot with a syllabus attached.

A flat list of topic scores can tell you *that* a student failed projectile motion. It
cannot tell you they failed it because vector decomposition — two prerequisites upstream
— has been quietly broken for three topics. Teaching projectile motion again would waste
their afternoon. The graph is what turns a symptom into a root cause.

It also does double duty: a topological walk gated by mastery is exactly the
Duolingo-style course path, so the same structure drives both diagnosis and progression.

Graphs are generated by the curriculum agent from a raw syllabus, which means they are
model output and cannot be trusted to be acyclic. Every traversal here is cycle-safe.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

# Below this, a concept counts as not yet learned. Deliberately generous -- the cost of
# re-teaching something a student already knows is boredom; the cost of building on a
# cracked foundation is that everything downstream silently fails.
MASTERY_THRESHOLD = 0.7


@dataclass
class Concept:
    id: str
    name: str
    name_local: str | None = None
    unit: str | None = None
    prereqs: list[str] = field(default_factory=list)

    def label(self, language: str = "en") -> str:
        return self.name_local if (language != "en" and self.name_local) else self.name


class KnowledgeGraph:
    def __init__(self, concepts: list[Concept]) -> None:
        self.concepts: dict[str, Concept] = {c.id: c for c in concepts}
        self._validate()

    def _validate(self) -> None:
        """Drop edges pointing at concepts that don't exist.

        The curriculum agent hallucinates prerequisite ids occasionally. A dangling edge
        would otherwise surface much later as a confusing empty traversal, so we prune
        loudly at construction instead.
        """
        for c in self.concepts.values():
            missing = [p for p in c.prereqs if p not in self.concepts]
            if missing:
                print(f"!! concept {c.id!r} has unknown prereqs {missing}, dropping")
                c.prereqs = [p for p in c.prereqs if p in self.concepts]

    # ---------------------------------------------------------------- loading

    @classmethod
    def from_dicts(cls, raw: list[dict]) -> "KnowledgeGraph":
        return cls([Concept(**r) for r in raw])

    @classmethod
    def load(cls, path: Path | str) -> "KnowledgeGraph":
        data = json.loads(Path(path).read_text())
        return cls.from_dicts(data["concepts"] if isinstance(data, dict) else data)

    def save(self, path: Path | str) -> None:
        payload = {"concepts": [c.__dict__ for c in self.concepts.values()]}
        Path(path).write_text(json.dumps(payload, ensure_ascii=False, indent=2))

    def break_cycles(self) -> list[tuple[str, str]]:
        """Remove back edges until the graph is acyclic. Returns what was cut.

        Tolerating a cycle is not enough. Two concepts that require each other are
        *permanently* locked -- `unlocked()` needs every prerequisite mastered, and
        neither can ever qualify. The student would simply never be offered them, with
        no error anywhere to explain why.

        The curriculum agent produces mutual dependencies fairly readily (momentum
        conservation and collisions genuinely are taught together, so a model asked
        "what must come first" can answer "each other"). Since some edge has to go, we
        cut the one closing the cycle and record it, rather than guessing which
        direction the author meant.
        """
        removed: list[tuple[str, str]] = []
        WHITE, GRAY, BLACK = 0, 1, 2
        colour = {cid: WHITE for cid in self.concepts}

        def visit(start: str) -> None:
            # Explicit stack: a deep syllabus graph can exceed recursion limits, and
            # blowing the stack mid-demo is not a failure mode worth risking.
            stack: list[tuple[str, int]] = [(start, 0)]
            while stack:
                cid, idx = stack[-1]
                if idx == 0:
                    colour[cid] = GRAY
                prereqs = self.concepts[cid].prereqs
                if idx < len(prereqs):
                    stack[-1] = (cid, idx + 1)
                    nxt = prereqs[idx]
                    if colour[nxt] == GRAY:
                        # Back edge: cid depends on something still open in this path.
                        self.concepts[cid].prereqs.remove(nxt)
                        removed.append((cid, nxt))
                        stack[-1] = (cid, idx)  # list shifted under us
                    elif colour[nxt] == WHITE:
                        stack.append((nxt, 0))
                else:
                    colour[cid] = BLACK
                    stack.pop()

        for cid in sorted(self.concepts):
            if colour[cid] == WHITE:
                visit(cid)

        if removed:
            desc = ", ".join(f"{a} -/-> {b}" for a, b in removed)
            print(f"!! broke {len(removed)} cyclic prereq edge(s): {desc}")
        return removed

    # ------------------------------------------------------------- traversal

    def ancestors(self, concept_id: str) -> list[str]:
        """All transitive prerequisites, nearest first. Cycle-safe."""
        seen: set[str] = set()
        order: list[str] = []
        frontier = list(self.concepts[concept_id].prereqs) if concept_id in self.concepts else []

        while frontier:
            cid = frontier.pop(0)
            if cid in seen:
                continue
            seen.add(cid)
            order.append(cid)
            frontier.extend(self.concepts[cid].prereqs)
        return order

    def root_cause(
        self, concept_id: str, mastery: dict[str, float]
    ) -> str | None:
        """The most upstream weak concept behind a failure at `concept_id`.

        Returns the weak ancestor that has no weak ancestors of its own -- fixing that
        one unblocks everything downstream of it. Returns None when the prerequisites
        are all solid, which means the student genuinely just needs this concept taught.

        Falling back to `concept_id` itself when nothing upstream is weak would be
        wrong: "you need to relearn the thing you just got wrong" is not a diagnosis.

        Only concepts the student has actually *attempted* can be a root cause. A
        concept absent from `mastery` has no evidence either way, and treating absence
        as failure makes this walk all the way to the first concept in the syllabus and
        blame that -- which is both wrong and useless, since the earliest concept is
        upstream of everything. Not-yet-covered material is the course path's job
        (`next_concept`), not the diagnostician's.
        """
        weak = {
            cid
            for cid in self.ancestors(concept_id)
            if cid in mastery and mastery[cid] < MASTERY_THRESHOLD
        }
        if not weak:
            return None

        # A weak concept whose own prerequisites are all fine is the root of the problem.
        for cid in weak:
            if not any(p in weak for p in self.concepts[cid].prereqs):
                return cid

        # Every weak concept has a weak prerequisite -- only possible under a cycle.
        # Return something useful rather than nothing.
        return next(iter(weak))

    def unlocked(self, mastery: dict[str, float]) -> list[str]:
        """Concepts whose prerequisites are satisfied but which aren't yet mastered.

        This is the Duolingo mechanic: the set of things the student may start next.

        Note this treats an unattempted concept as *not mastered* (default 0.0), which
        is the opposite of `root_cause`, where absence of evidence is not treated as
        weakness. That difference is deliberate, not an oversight: "what should you
        study next" must include everything you have not done yet, while "why did you
        just fail" may only cite things we actually observed you failing.
        """
        ready = []
        for c in self.concepts.values():
            if mastery.get(c.id, 0.0) >= MASTERY_THRESHOLD:
                continue
            if all(mastery.get(p, 0.0) >= MASTERY_THRESHOLD for p in c.prereqs):
                ready.append(c.id)
        return ready

    def course_path(self) -> list[str]:
        """Full ordering of the course, prerequisites before dependents.

        Kahn's algorithm. If a cycle exists the remaining nodes are appended in a stable
        order rather than dropped -- a partially-wrong ordering is recoverable in a demo,
        a course that silently loses half its concepts is not.
        """
        indegree = {cid: 0 for cid in self.concepts}
        dependents: dict[str, list[str]] = {cid: [] for cid in self.concepts}
        for c in self.concepts.values():
            for p in c.prereqs:
                indegree[c.id] += 1
                dependents[p].append(c.id)

        queue = sorted([cid for cid, d in indegree.items() if d == 0])
        order: list[str] = []
        while queue:
            cid = queue.pop(0)
            order.append(cid)
            for dep in dependents[cid]:
                indegree[dep] -= 1
                if indegree[dep] == 0:
                    queue.append(dep)
            queue.sort()

        if len(order) < len(self.concepts):
            leftover = sorted(set(self.concepts) - set(order))
            print(f"!! cycle in knowledge graph; appending {len(leftover)} concept(s)")
            order.extend(leftover)
        return order

    def next_concept(self, mastery: dict[str, float]) -> str | None:
        """What the student should study next: first unlocked concept in course order."""
        ready = set(self.unlocked(mastery))
        return next((cid for cid in self.course_path() if cid in ready), None)

    def describe(self, concept_id: str, language: str = "en") -> str:
        """Human-readable label, for use inside prompts."""
        c = self.concepts.get(concept_id)
        return c.label(language) if c else concept_id
